// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cap.proto

package com.google.publicalerts.cap;

/**
 * <pre>
 * The paired values of a point and radius delineating the affected area of
 * the alert message.
 * </pre>
 *
 * Protobuf type {@code publicalerts.cap.Circle}
 */
public  final class Circle extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:publicalerts.cap.Circle)
    CircleOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Circle.newBuilder() to construct.
  private Circle(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Circle() {
    radius_ = 0D;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Circle(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.google.publicalerts.cap.Point.Builder subBuilder = null;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
              subBuilder = point_.toBuilder();
            }
            point_ = input.readMessage(com.google.publicalerts.cap.Point.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(point_);
              point_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000001;
            break;
          }
          case 17: {
            bitField0_ |= 0x00000002;
            radius_ = input.readDouble();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.publicalerts.cap.Cap.internal_static_publicalerts_cap_Circle_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.publicalerts.cap.Cap.internal_static_publicalerts_cap_Circle_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.publicalerts.cap.Circle.class, com.google.publicalerts.cap.Circle.Builder.class);
  }

  private int bitField0_;
  public static final int POINT_FIELD_NUMBER = 1;
  private com.google.publicalerts.cap.Point point_;
  /**
   * <code>required .publicalerts.cap.Point point = 1;</code>
   */
  public boolean hasPoint() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>required .publicalerts.cap.Point point = 1;</code>
   */
  public com.google.publicalerts.cap.Point getPoint() {
    return point_ == null ? com.google.publicalerts.cap.Point.getDefaultInstance() : point_;
  }
  /**
   * <code>required .publicalerts.cap.Point point = 1;</code>
   */
  public com.google.publicalerts.cap.PointOrBuilder getPointOrBuilder() {
    return point_ == null ? com.google.publicalerts.cap.Point.getDefaultInstance() : point_;
  }

  public static final int RADIUS_FIELD_NUMBER = 2;
  private double radius_;
  /**
   * <pre>
   * Radius is expressed in kilometers.
   * </pre>
   *
   * <code>required double radius = 2;</code>
   */
  public boolean hasRadius() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <pre>
   * Radius is expressed in kilometers.
   * </pre>
   *
   * <code>required double radius = 2;</code>
   */
  public double getRadius() {
    return radius_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasPoint()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasRadius()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!getPoint().isInitialized()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeMessage(1, getPoint());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeDouble(2, radius_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getPoint());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(2, radius_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.publicalerts.cap.Circle)) {
      return super.equals(obj);
    }
    com.google.publicalerts.cap.Circle other = (com.google.publicalerts.cap.Circle) obj;

    boolean result = true;
    result = result && (hasPoint() == other.hasPoint());
    if (hasPoint()) {
      result = result && getPoint()
          .equals(other.getPoint());
    }
    result = result && (hasRadius() == other.hasRadius());
    if (hasRadius()) {
      result = result && (
          java.lang.Double.doubleToLongBits(getRadius())
          == java.lang.Double.doubleToLongBits(
              other.getRadius()));
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasPoint()) {
      hash = (37 * hash) + POINT_FIELD_NUMBER;
      hash = (53 * hash) + getPoint().hashCode();
    }
    if (hasRadius()) {
      hash = (37 * hash) + RADIUS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getRadius()));
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.publicalerts.cap.Circle parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.publicalerts.cap.Circle parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.publicalerts.cap.Circle parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.publicalerts.cap.Circle parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.publicalerts.cap.Circle parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.publicalerts.cap.Circle parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.publicalerts.cap.Circle parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.publicalerts.cap.Circle parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.publicalerts.cap.Circle parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.google.publicalerts.cap.Circle parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.publicalerts.cap.Circle parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.publicalerts.cap.Circle parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.publicalerts.cap.Circle prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * The paired values of a point and radius delineating the affected area of
   * the alert message.
   * </pre>
   *
   * Protobuf type {@code publicalerts.cap.Circle}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:publicalerts.cap.Circle)
      com.google.publicalerts.cap.CircleOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.publicalerts.cap.Cap.internal_static_publicalerts_cap_Circle_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.publicalerts.cap.Cap.internal_static_publicalerts_cap_Circle_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.publicalerts.cap.Circle.class, com.google.publicalerts.cap.Circle.Builder.class);
    }

    // Construct using com.google.publicalerts.cap.Circle.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getPointFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (pointBuilder_ == null) {
        point_ = null;
      } else {
        pointBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      radius_ = 0D;
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.publicalerts.cap.Cap.internal_static_publicalerts_cap_Circle_descriptor;
    }

    @java.lang.Override
    public com.google.publicalerts.cap.Circle getDefaultInstanceForType() {
      return com.google.publicalerts.cap.Circle.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.publicalerts.cap.Circle build() {
      com.google.publicalerts.cap.Circle result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.publicalerts.cap.Circle buildPartial() {
      com.google.publicalerts.cap.Circle result = new com.google.publicalerts.cap.Circle(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      if (pointBuilder_ == null) {
        result.point_ = point_;
      } else {
        result.point_ = pointBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.radius_ = radius_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.publicalerts.cap.Circle) {
        return mergeFrom((com.google.publicalerts.cap.Circle)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.publicalerts.cap.Circle other) {
      if (other == com.google.publicalerts.cap.Circle.getDefaultInstance()) return this;
      if (other.hasPoint()) {
        mergePoint(other.getPoint());
      }
      if (other.hasRadius()) {
        setRadius(other.getRadius());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      if (!hasPoint()) {
        return false;
      }
      if (!hasRadius()) {
        return false;
      }
      if (!getPoint().isInitialized()) {
        return false;
      }
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.google.publicalerts.cap.Circle parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.google.publicalerts.cap.Circle) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.publicalerts.cap.Point point_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.publicalerts.cap.Point, com.google.publicalerts.cap.Point.Builder, com.google.publicalerts.cap.PointOrBuilder> pointBuilder_;
    /**
     * <code>required .publicalerts.cap.Point point = 1;</code>
     */
    public boolean hasPoint() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .publicalerts.cap.Point point = 1;</code>
     */
    public com.google.publicalerts.cap.Point getPoint() {
      if (pointBuilder_ == null) {
        return point_ == null ? com.google.publicalerts.cap.Point.getDefaultInstance() : point_;
      } else {
        return pointBuilder_.getMessage();
      }
    }
    /**
     * <code>required .publicalerts.cap.Point point = 1;</code>
     */
    public Builder setPoint(com.google.publicalerts.cap.Point value) {
      if (pointBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        point_ = value;
        onChanged();
      } else {
        pointBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>required .publicalerts.cap.Point point = 1;</code>
     */
    public Builder setPoint(
        com.google.publicalerts.cap.Point.Builder builderForValue) {
      if (pointBuilder_ == null) {
        point_ = builderForValue.build();
        onChanged();
      } else {
        pointBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>required .publicalerts.cap.Point point = 1;</code>
     */
    public Builder mergePoint(com.google.publicalerts.cap.Point value) {
      if (pointBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001) &&
            point_ != null &&
            point_ != com.google.publicalerts.cap.Point.getDefaultInstance()) {
          point_ =
            com.google.publicalerts.cap.Point.newBuilder(point_).mergeFrom(value).buildPartial();
        } else {
          point_ = value;
        }
        onChanged();
      } else {
        pointBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>required .publicalerts.cap.Point point = 1;</code>
     */
    public Builder clearPoint() {
      if (pointBuilder_ == null) {
        point_ = null;
        onChanged();
      } else {
        pointBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }
    /**
     * <code>required .publicalerts.cap.Point point = 1;</code>
     */
    public com.google.publicalerts.cap.Point.Builder getPointBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getPointFieldBuilder().getBuilder();
    }
    /**
     * <code>required .publicalerts.cap.Point point = 1;</code>
     */
    public com.google.publicalerts.cap.PointOrBuilder getPointOrBuilder() {
      if (pointBuilder_ != null) {
        return pointBuilder_.getMessageOrBuilder();
      } else {
        return point_ == null ?
            com.google.publicalerts.cap.Point.getDefaultInstance() : point_;
      }
    }
    /**
     * <code>required .publicalerts.cap.Point point = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.publicalerts.cap.Point, com.google.publicalerts.cap.Point.Builder, com.google.publicalerts.cap.PointOrBuilder> 
        getPointFieldBuilder() {
      if (pointBuilder_ == null) {
        pointBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.publicalerts.cap.Point, com.google.publicalerts.cap.Point.Builder, com.google.publicalerts.cap.PointOrBuilder>(
                getPoint(),
                getParentForChildren(),
                isClean());
        point_ = null;
      }
      return pointBuilder_;
    }

    private double radius_ ;
    /**
     * <pre>
     * Radius is expressed in kilometers.
     * </pre>
     *
     * <code>required double radius = 2;</code>
     */
    public boolean hasRadius() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     * Radius is expressed in kilometers.
     * </pre>
     *
     * <code>required double radius = 2;</code>
     */
    public double getRadius() {
      return radius_;
    }
    /**
     * <pre>
     * Radius is expressed in kilometers.
     * </pre>
     *
     * <code>required double radius = 2;</code>
     */
    public Builder setRadius(double value) {
      bitField0_ |= 0x00000002;
      radius_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Radius is expressed in kilometers.
     * </pre>
     *
     * <code>required double radius = 2;</code>
     */
    public Builder clearRadius() {
      bitField0_ = (bitField0_ & ~0x00000002);
      radius_ = 0D;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:publicalerts.cap.Circle)
  }

  // @@protoc_insertion_point(class_scope:publicalerts.cap.Circle)
  private static final com.google.publicalerts.cap.Circle DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.publicalerts.cap.Circle();
  }

  public static com.google.publicalerts.cap.Circle getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<Circle>
      PARSER = new com.google.protobuf.AbstractParser<Circle>() {
    @java.lang.Override
    public Circle parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Circle(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Circle> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Circle> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.publicalerts.cap.Circle getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

