// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cap.proto

package com.google.publicalerts.cap;

public interface CircleOrBuilder extends
    // @@protoc_insertion_point(interface_extends:publicalerts.cap.Circle)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required .publicalerts.cap.Point point = 1;</code>
   */
  boolean hasPoint();
  /**
   * <code>required .publicalerts.cap.Point point = 1;</code>
   */
  com.google.publicalerts.cap.Point getPoint();
  /**
   * <code>required .publicalerts.cap.Point point = 1;</code>
   */
  com.google.publicalerts.cap.PointOrBuilder getPointOrBuilder();

  /**
   * <pre>
   * Radius is expressed in kilometers.
   * </pre>
   *
   * <code>required double radius = 2;</code>
   */
  boolean hasRadius();
  /**
   * <pre>
   * Radius is expressed in kilometers.
   * </pre>
   *
   * <code>required double radius = 2;</code>
   */
  double getRadius();
}
