// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cap.proto

package com.google.publicalerts.cap;

public interface GroupOrBuilder extends
    // @@protoc_insertion_point(interface_extends:publicalerts.cap.Group)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string value = 1;</code>
   */
  java.util.List<java.lang.String>
      getValueList();
  /**
   * <code>repeated string value = 1;</code>
   */
  int getValueCount();
  /**
   * <code>repeated string value = 1;</code>
   */
  java.lang.String getValue(int index);
  /**
   * <code>repeated string value = 1;</code>
   */
  com.google.protobuf.ByteString
      getValueBytes(int index);
}
