// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cap.proto

package com.google.publicalerts.cap;

public interface PointOrBuilder extends
    // @@protoc_insertion_point(interface_extends:publicalerts.cap.Point)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required double latitude = 1;</code>
   */
  boolean hasLatitude();
  /**
   * <code>required double latitude = 1;</code>
   */
  double getLatitude();

  /**
   * <code>required double longitude = 2;</code>
   */
  boolean hasLongitude();
  /**
   * <code>required double longitude = 2;</code>
   */
  double getLongitude();
}
