// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cap.proto

package com.google.publicalerts.cap;

/**
 * <pre>
 * The container for all component parts of the resource sub-element of
 * the info sub-element of the alert message.
 * </pre>
 *
 * Protobuf type {@code publicalerts.cap.Resource}
 */
public  final class Resource extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:publicalerts.cap.Resource)
    ResourceOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Resource.newBuilder() to construct.
  private Resource(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Resource() {
    resourceDesc_ = "";
    mimeType_ = "";
    size_ = 0L;
    uri_ = "";
    derefUri_ = "";
    digest_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Resource(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000001;
            resourceDesc_ = bs;
            break;
          }
          case 18: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000002;
            mimeType_ = bs;
            break;
          }
          case 24: {
            bitField0_ |= 0x00000004;
            size_ = input.readInt64();
            break;
          }
          case 34: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000008;
            uri_ = bs;
            break;
          }
          case 42: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000010;
            derefUri_ = bs;
            break;
          }
          case 50: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000020;
            digest_ = bs;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.publicalerts.cap.Cap.internal_static_publicalerts_cap_Resource_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.publicalerts.cap.Cap.internal_static_publicalerts_cap_Resource_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.publicalerts.cap.Resource.class, com.google.publicalerts.cap.Resource.Builder.class);
  }

  private int bitField0_;
  public static final int RESOURCE_DESC_FIELD_NUMBER = 1;
  private volatile java.lang.Object resourceDesc_;
  /**
   * <pre>
   * The human-readable text describing the content and kind, such as
   * "map" or "photo", of the resource file
   * </pre>
   *
   * <code>required string resource_desc = 1;</code>
   */
  public boolean hasResourceDesc() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <pre>
   * The human-readable text describing the content and kind, such as
   * "map" or "photo", of the resource file
   * </pre>
   *
   * <code>required string resource_desc = 1;</code>
   */
  public java.lang.String getResourceDesc() {
    java.lang.Object ref = resourceDesc_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        resourceDesc_ = s;
      }
      return s;
    }
  }
  /**
   * <pre>
   * The human-readable text describing the content and kind, such as
   * "map" or "photo", of the resource file
   * </pre>
   *
   * <code>required string resource_desc = 1;</code>
   */
  public com.google.protobuf.ByteString
      getResourceDescBytes() {
    java.lang.Object ref = resourceDesc_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      resourceDesc_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MIME_TYPE_FIELD_NUMBER = 2;
  private volatile java.lang.Object mimeType_;
  /**
   * <pre>
   * MIME content type and sub-type as described in [RFC 2046].
   * (As of this document, the current IANA registered MIME types are
   * listed at http://www.iana.org/assignments/media-types/)
   * Required as of CAP 1.2
   * </pre>
   *
   * <code>optional string mime_type = 2;</code>
   */
  public boolean hasMimeType() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <pre>
   * MIME content type and sub-type as described in [RFC 2046].
   * (As of this document, the current IANA registered MIME types are
   * listed at http://www.iana.org/assignments/media-types/)
   * Required as of CAP 1.2
   * </pre>
   *
   * <code>optional string mime_type = 2;</code>
   */
  public java.lang.String getMimeType() {
    java.lang.Object ref = mimeType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        mimeType_ = s;
      }
      return s;
    }
  }
  /**
   * <pre>
   * MIME content type and sub-type as described in [RFC 2046].
   * (As of this document, the current IANA registered MIME types are
   * listed at http://www.iana.org/assignments/media-types/)
   * Required as of CAP 1.2
   * </pre>
   *
   * <code>optional string mime_type = 2;</code>
   */
  public com.google.protobuf.ByteString
      getMimeTypeBytes() {
    java.lang.Object ref = mimeType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      mimeType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SIZE_FIELD_NUMBER = 3;
  private long size_;
  /**
   * <pre>
   * Approximate size of the resource file in bytes.
   * </pre>
   *
   * <code>optional int64 size = 3;</code>
   */
  public boolean hasSize() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <pre>
   * Approximate size of the resource file in bytes.
   * </pre>
   *
   * <code>optional int64 size = 3;</code>
   */
  public long getSize() {
    return size_;
  }

  public static final int URI_FIELD_NUMBER = 4;
  private volatile java.lang.Object uri_;
  /**
   * <pre>
   * A full absolute URI, typically a Uniform Resource Locator that can
   * be used to retrieve the resource over the Internet
   * OR
   * a relative URI to name the content of a &lt;derefUri&gt; element if one is
   * present in this resource block.
   * </pre>
   *
   * <code>optional string uri = 4;</code>
   */
  public boolean hasUri() {
    return ((bitField0_ & 0x00000008) == 0x00000008);
  }
  /**
   * <pre>
   * A full absolute URI, typically a Uniform Resource Locator that can
   * be used to retrieve the resource over the Internet
   * OR
   * a relative URI to name the content of a &lt;derefUri&gt; element if one is
   * present in this resource block.
   * </pre>
   *
   * <code>optional string uri = 4;</code>
   */
  public java.lang.String getUri() {
    java.lang.Object ref = uri_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        uri_ = s;
      }
      return s;
    }
  }
  /**
   * <pre>
   * A full absolute URI, typically a Uniform Resource Locator that can
   * be used to retrieve the resource over the Internet
   * OR
   * a relative URI to name the content of a &lt;derefUri&gt; element if one is
   * present in this resource block.
   * </pre>
   *
   * <code>optional string uri = 4;</code>
   */
  public com.google.protobuf.ByteString
      getUriBytes() {
    java.lang.Object ref = uri_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      uri_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DEREF_URI_FIELD_NUMBER = 5;
  private volatile java.lang.Object derefUri_;
  /**
   * <pre>
   * The base-64 encoded data content of the resource file.
   * MAY be used either with or instead of the &lt;uri&gt; element in messages
   * transmitted over one-way (e.g., broadcast) data links where retrieval
   * of a resource via a URI is not feasible.
   * Clients intended for use with one-way data links MUST support this
   * element.
   * This element MUST NOT be used unless the sender is certain that all
   * direct clients are capable of processing it.
   * If messages including this element are forwarded onto a two-way
   * network, the forwarder MUST strip the &lt;derefUri&gt; element and SHOULD
   * extract the file contents and provide a &lt;uri&gt; link to a
   * retrievable version of the file.
   * Providers of one-way data links MAY enforce additional restrictions
   * on the use of this element, including message-size limits and
   * restrictions regarding file types.
   * Added in CAP 1.1
   * </pre>
   *
   * <code>optional string deref_uri = 5;</code>
   */
  public boolean hasDerefUri() {
    return ((bitField0_ & 0x00000010) == 0x00000010);
  }
  /**
   * <pre>
   * The base-64 encoded data content of the resource file.
   * MAY be used either with or instead of the &lt;uri&gt; element in messages
   * transmitted over one-way (e.g., broadcast) data links where retrieval
   * of a resource via a URI is not feasible.
   * Clients intended for use with one-way data links MUST support this
   * element.
   * This element MUST NOT be used unless the sender is certain that all
   * direct clients are capable of processing it.
   * If messages including this element are forwarded onto a two-way
   * network, the forwarder MUST strip the &lt;derefUri&gt; element and SHOULD
   * extract the file contents and provide a &lt;uri&gt; link to a
   * retrievable version of the file.
   * Providers of one-way data links MAY enforce additional restrictions
   * on the use of this element, including message-size limits and
   * restrictions regarding file types.
   * Added in CAP 1.1
   * </pre>
   *
   * <code>optional string deref_uri = 5;</code>
   */
  public java.lang.String getDerefUri() {
    java.lang.Object ref = derefUri_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        derefUri_ = s;
      }
      return s;
    }
  }
  /**
   * <pre>
   * The base-64 encoded data content of the resource file.
   * MAY be used either with or instead of the &lt;uri&gt; element in messages
   * transmitted over one-way (e.g., broadcast) data links where retrieval
   * of a resource via a URI is not feasible.
   * Clients intended for use with one-way data links MUST support this
   * element.
   * This element MUST NOT be used unless the sender is certain that all
   * direct clients are capable of processing it.
   * If messages including this element are forwarded onto a two-way
   * network, the forwarder MUST strip the &lt;derefUri&gt; element and SHOULD
   * extract the file contents and provide a &lt;uri&gt; link to a
   * retrievable version of the file.
   * Providers of one-way data links MAY enforce additional restrictions
   * on the use of this element, including message-size limits and
   * restrictions regarding file types.
   * Added in CAP 1.1
   * </pre>
   *
   * <code>optional string deref_uri = 5;</code>
   */
  public com.google.protobuf.ByteString
      getDerefUriBytes() {
    java.lang.Object ref = derefUri_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      derefUri_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DIGEST_FIELD_NUMBER = 6;
  private volatile java.lang.Object digest_;
  /**
   * <pre>
   * The code representing the digital digest (?hash?) computed from the
   * resource from the resource file. Calculated using the Secure Hash
   * Algorithm (SHA-1) per [FIPS 180-2]
   * </pre>
   *
   * <code>optional string digest = 6;</code>
   */
  public boolean hasDigest() {
    return ((bitField0_ & 0x00000020) == 0x00000020);
  }
  /**
   * <pre>
   * The code representing the digital digest (?hash?) computed from the
   * resource from the resource file. Calculated using the Secure Hash
   * Algorithm (SHA-1) per [FIPS 180-2]
   * </pre>
   *
   * <code>optional string digest = 6;</code>
   */
  public java.lang.String getDigest() {
    java.lang.Object ref = digest_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        digest_ = s;
      }
      return s;
    }
  }
  /**
   * <pre>
   * The code representing the digital digest (?hash?) computed from the
   * resource from the resource file. Calculated using the Secure Hash
   * Algorithm (SHA-1) per [FIPS 180-2]
   * </pre>
   *
   * <code>optional string digest = 6;</code>
   */
  public com.google.protobuf.ByteString
      getDigestBytes() {
    java.lang.Object ref = digest_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      digest_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasResourceDesc()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, resourceDesc_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, mimeType_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      output.writeInt64(3, size_);
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, uri_);
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, derefUri_);
    }
    if (((bitField0_ & 0x00000020) == 0x00000020)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, digest_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, resourceDesc_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, mimeType_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, size_);
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, uri_);
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, derefUri_);
    }
    if (((bitField0_ & 0x00000020) == 0x00000020)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, digest_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.publicalerts.cap.Resource)) {
      return super.equals(obj);
    }
    com.google.publicalerts.cap.Resource other = (com.google.publicalerts.cap.Resource) obj;

    boolean result = true;
    result = result && (hasResourceDesc() == other.hasResourceDesc());
    if (hasResourceDesc()) {
      result = result && getResourceDesc()
          .equals(other.getResourceDesc());
    }
    result = result && (hasMimeType() == other.hasMimeType());
    if (hasMimeType()) {
      result = result && getMimeType()
          .equals(other.getMimeType());
    }
    result = result && (hasSize() == other.hasSize());
    if (hasSize()) {
      result = result && (getSize()
          == other.getSize());
    }
    result = result && (hasUri() == other.hasUri());
    if (hasUri()) {
      result = result && getUri()
          .equals(other.getUri());
    }
    result = result && (hasDerefUri() == other.hasDerefUri());
    if (hasDerefUri()) {
      result = result && getDerefUri()
          .equals(other.getDerefUri());
    }
    result = result && (hasDigest() == other.hasDigest());
    if (hasDigest()) {
      result = result && getDigest()
          .equals(other.getDigest());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasResourceDesc()) {
      hash = (37 * hash) + RESOURCE_DESC_FIELD_NUMBER;
      hash = (53 * hash) + getResourceDesc().hashCode();
    }
    if (hasMimeType()) {
      hash = (37 * hash) + MIME_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getMimeType().hashCode();
    }
    if (hasSize()) {
      hash = (37 * hash) + SIZE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSize());
    }
    if (hasUri()) {
      hash = (37 * hash) + URI_FIELD_NUMBER;
      hash = (53 * hash) + getUri().hashCode();
    }
    if (hasDerefUri()) {
      hash = (37 * hash) + DEREF_URI_FIELD_NUMBER;
      hash = (53 * hash) + getDerefUri().hashCode();
    }
    if (hasDigest()) {
      hash = (37 * hash) + DIGEST_FIELD_NUMBER;
      hash = (53 * hash) + getDigest().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.publicalerts.cap.Resource parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.publicalerts.cap.Resource parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.publicalerts.cap.Resource parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.publicalerts.cap.Resource parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.publicalerts.cap.Resource parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.publicalerts.cap.Resource parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.publicalerts.cap.Resource parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.publicalerts.cap.Resource parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.publicalerts.cap.Resource parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.google.publicalerts.cap.Resource parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.publicalerts.cap.Resource parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.publicalerts.cap.Resource parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.publicalerts.cap.Resource prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * The container for all component parts of the resource sub-element of
   * the info sub-element of the alert message.
   * </pre>
   *
   * Protobuf type {@code publicalerts.cap.Resource}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:publicalerts.cap.Resource)
      com.google.publicalerts.cap.ResourceOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.publicalerts.cap.Cap.internal_static_publicalerts_cap_Resource_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.publicalerts.cap.Cap.internal_static_publicalerts_cap_Resource_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.publicalerts.cap.Resource.class, com.google.publicalerts.cap.Resource.Builder.class);
    }

    // Construct using com.google.publicalerts.cap.Resource.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      resourceDesc_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      mimeType_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      size_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000004);
      uri_ = "";
      bitField0_ = (bitField0_ & ~0x00000008);
      derefUri_ = "";
      bitField0_ = (bitField0_ & ~0x00000010);
      digest_ = "";
      bitField0_ = (bitField0_ & ~0x00000020);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.publicalerts.cap.Cap.internal_static_publicalerts_cap_Resource_descriptor;
    }

    @java.lang.Override
    public com.google.publicalerts.cap.Resource getDefaultInstanceForType() {
      return com.google.publicalerts.cap.Resource.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.publicalerts.cap.Resource build() {
      com.google.publicalerts.cap.Resource result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.publicalerts.cap.Resource buildPartial() {
      com.google.publicalerts.cap.Resource result = new com.google.publicalerts.cap.Resource(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.resourceDesc_ = resourceDesc_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.mimeType_ = mimeType_;
      if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
        to_bitField0_ |= 0x00000004;
      }
      result.size_ = size_;
      if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
        to_bitField0_ |= 0x00000008;
      }
      result.uri_ = uri_;
      if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
        to_bitField0_ |= 0x00000010;
      }
      result.derefUri_ = derefUri_;
      if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
        to_bitField0_ |= 0x00000020;
      }
      result.digest_ = digest_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.publicalerts.cap.Resource) {
        return mergeFrom((com.google.publicalerts.cap.Resource)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.publicalerts.cap.Resource other) {
      if (other == com.google.publicalerts.cap.Resource.getDefaultInstance()) return this;
      if (other.hasResourceDesc()) {
        bitField0_ |= 0x00000001;
        resourceDesc_ = other.resourceDesc_;
        onChanged();
      }
      if (other.hasMimeType()) {
        bitField0_ |= 0x00000002;
        mimeType_ = other.mimeType_;
        onChanged();
      }
      if (other.hasSize()) {
        setSize(other.getSize());
      }
      if (other.hasUri()) {
        bitField0_ |= 0x00000008;
        uri_ = other.uri_;
        onChanged();
      }
      if (other.hasDerefUri()) {
        bitField0_ |= 0x00000010;
        derefUri_ = other.derefUri_;
        onChanged();
      }
      if (other.hasDigest()) {
        bitField0_ |= 0x00000020;
        digest_ = other.digest_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      if (!hasResourceDesc()) {
        return false;
      }
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.google.publicalerts.cap.Resource parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.google.publicalerts.cap.Resource) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object resourceDesc_ = "";
    /**
     * <pre>
     * The human-readable text describing the content and kind, such as
     * "map" or "photo", of the resource file
     * </pre>
     *
     * <code>required string resource_desc = 1;</code>
     */
    public boolean hasResourceDesc() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     * The human-readable text describing the content and kind, such as
     * "map" or "photo", of the resource file
     * </pre>
     *
     * <code>required string resource_desc = 1;</code>
     */
    public java.lang.String getResourceDesc() {
      java.lang.Object ref = resourceDesc_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          resourceDesc_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The human-readable text describing the content and kind, such as
     * "map" or "photo", of the resource file
     * </pre>
     *
     * <code>required string resource_desc = 1;</code>
     */
    public com.google.protobuf.ByteString
        getResourceDescBytes() {
      java.lang.Object ref = resourceDesc_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        resourceDesc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The human-readable text describing the content and kind, such as
     * "map" or "photo", of the resource file
     * </pre>
     *
     * <code>required string resource_desc = 1;</code>
     */
    public Builder setResourceDesc(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      resourceDesc_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The human-readable text describing the content and kind, such as
     * "map" or "photo", of the resource file
     * </pre>
     *
     * <code>required string resource_desc = 1;</code>
     */
    public Builder clearResourceDesc() {
      bitField0_ = (bitField0_ & ~0x00000001);
      resourceDesc_ = getDefaultInstance().getResourceDesc();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The human-readable text describing the content and kind, such as
     * "map" or "photo", of the resource file
     * </pre>
     *
     * <code>required string resource_desc = 1;</code>
     */
    public Builder setResourceDescBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      resourceDesc_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object mimeType_ = "";
    /**
     * <pre>
     * MIME content type and sub-type as described in [RFC 2046].
     * (As of this document, the current IANA registered MIME types are
     * listed at http://www.iana.org/assignments/media-types/)
     * Required as of CAP 1.2
     * </pre>
     *
     * <code>optional string mime_type = 2;</code>
     */
    public boolean hasMimeType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     * MIME content type and sub-type as described in [RFC 2046].
     * (As of this document, the current IANA registered MIME types are
     * listed at http://www.iana.org/assignments/media-types/)
     * Required as of CAP 1.2
     * </pre>
     *
     * <code>optional string mime_type = 2;</code>
     */
    public java.lang.String getMimeType() {
      java.lang.Object ref = mimeType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          mimeType_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * MIME content type and sub-type as described in [RFC 2046].
     * (As of this document, the current IANA registered MIME types are
     * listed at http://www.iana.org/assignments/media-types/)
     * Required as of CAP 1.2
     * </pre>
     *
     * <code>optional string mime_type = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMimeTypeBytes() {
      java.lang.Object ref = mimeType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mimeType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * MIME content type and sub-type as described in [RFC 2046].
     * (As of this document, the current IANA registered MIME types are
     * listed at http://www.iana.org/assignments/media-types/)
     * Required as of CAP 1.2
     * </pre>
     *
     * <code>optional string mime_type = 2;</code>
     */
    public Builder setMimeType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      mimeType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * MIME content type and sub-type as described in [RFC 2046].
     * (As of this document, the current IANA registered MIME types are
     * listed at http://www.iana.org/assignments/media-types/)
     * Required as of CAP 1.2
     * </pre>
     *
     * <code>optional string mime_type = 2;</code>
     */
    public Builder clearMimeType() {
      bitField0_ = (bitField0_ & ~0x00000002);
      mimeType_ = getDefaultInstance().getMimeType();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * MIME content type and sub-type as described in [RFC 2046].
     * (As of this document, the current IANA registered MIME types are
     * listed at http://www.iana.org/assignments/media-types/)
     * Required as of CAP 1.2
     * </pre>
     *
     * <code>optional string mime_type = 2;</code>
     */
    public Builder setMimeTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      mimeType_ = value;
      onChanged();
      return this;
    }

    private long size_ ;
    /**
     * <pre>
     * Approximate size of the resource file in bytes.
     * </pre>
     *
     * <code>optional int64 size = 3;</code>
     */
    public boolean hasSize() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <pre>
     * Approximate size of the resource file in bytes.
     * </pre>
     *
     * <code>optional int64 size = 3;</code>
     */
    public long getSize() {
      return size_;
    }
    /**
     * <pre>
     * Approximate size of the resource file in bytes.
     * </pre>
     *
     * <code>optional int64 size = 3;</code>
     */
    public Builder setSize(long value) {
      bitField0_ |= 0x00000004;
      size_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Approximate size of the resource file in bytes.
     * </pre>
     *
     * <code>optional int64 size = 3;</code>
     */
    public Builder clearSize() {
      bitField0_ = (bitField0_ & ~0x00000004);
      size_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object uri_ = "";
    /**
     * <pre>
     * A full absolute URI, typically a Uniform Resource Locator that can
     * be used to retrieve the resource over the Internet
     * OR
     * a relative URI to name the content of a &lt;derefUri&gt; element if one is
     * present in this resource block.
     * </pre>
     *
     * <code>optional string uri = 4;</code>
     */
    public boolean hasUri() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <pre>
     * A full absolute URI, typically a Uniform Resource Locator that can
     * be used to retrieve the resource over the Internet
     * OR
     * a relative URI to name the content of a &lt;derefUri&gt; element if one is
     * present in this resource block.
     * </pre>
     *
     * <code>optional string uri = 4;</code>
     */
    public java.lang.String getUri() {
      java.lang.Object ref = uri_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          uri_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * A full absolute URI, typically a Uniform Resource Locator that can
     * be used to retrieve the resource over the Internet
     * OR
     * a relative URI to name the content of a &lt;derefUri&gt; element if one is
     * present in this resource block.
     * </pre>
     *
     * <code>optional string uri = 4;</code>
     */
    public com.google.protobuf.ByteString
        getUriBytes() {
      java.lang.Object ref = uri_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uri_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * A full absolute URI, typically a Uniform Resource Locator that can
     * be used to retrieve the resource over the Internet
     * OR
     * a relative URI to name the content of a &lt;derefUri&gt; element if one is
     * present in this resource block.
     * </pre>
     *
     * <code>optional string uri = 4;</code>
     */
    public Builder setUri(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
      uri_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * A full absolute URI, typically a Uniform Resource Locator that can
     * be used to retrieve the resource over the Internet
     * OR
     * a relative URI to name the content of a &lt;derefUri&gt; element if one is
     * present in this resource block.
     * </pre>
     *
     * <code>optional string uri = 4;</code>
     */
    public Builder clearUri() {
      bitField0_ = (bitField0_ & ~0x00000008);
      uri_ = getDefaultInstance().getUri();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * A full absolute URI, typically a Uniform Resource Locator that can
     * be used to retrieve the resource over the Internet
     * OR
     * a relative URI to name the content of a &lt;derefUri&gt; element if one is
     * present in this resource block.
     * </pre>
     *
     * <code>optional string uri = 4;</code>
     */
    public Builder setUriBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
      uri_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object derefUri_ = "";
    /**
     * <pre>
     * The base-64 encoded data content of the resource file.
     * MAY be used either with or instead of the &lt;uri&gt; element in messages
     * transmitted over one-way (e.g., broadcast) data links where retrieval
     * of a resource via a URI is not feasible.
     * Clients intended for use with one-way data links MUST support this
     * element.
     * This element MUST NOT be used unless the sender is certain that all
     * direct clients are capable of processing it.
     * If messages including this element are forwarded onto a two-way
     * network, the forwarder MUST strip the &lt;derefUri&gt; element and SHOULD
     * extract the file contents and provide a &lt;uri&gt; link to a
     * retrievable version of the file.
     * Providers of one-way data links MAY enforce additional restrictions
     * on the use of this element, including message-size limits and
     * restrictions regarding file types.
     * Added in CAP 1.1
     * </pre>
     *
     * <code>optional string deref_uri = 5;</code>
     */
    public boolean hasDerefUri() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <pre>
     * The base-64 encoded data content of the resource file.
     * MAY be used either with or instead of the &lt;uri&gt; element in messages
     * transmitted over one-way (e.g., broadcast) data links where retrieval
     * of a resource via a URI is not feasible.
     * Clients intended for use with one-way data links MUST support this
     * element.
     * This element MUST NOT be used unless the sender is certain that all
     * direct clients are capable of processing it.
     * If messages including this element are forwarded onto a two-way
     * network, the forwarder MUST strip the &lt;derefUri&gt; element and SHOULD
     * extract the file contents and provide a &lt;uri&gt; link to a
     * retrievable version of the file.
     * Providers of one-way data links MAY enforce additional restrictions
     * on the use of this element, including message-size limits and
     * restrictions regarding file types.
     * Added in CAP 1.1
     * </pre>
     *
     * <code>optional string deref_uri = 5;</code>
     */
    public java.lang.String getDerefUri() {
      java.lang.Object ref = derefUri_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          derefUri_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The base-64 encoded data content of the resource file.
     * MAY be used either with or instead of the &lt;uri&gt; element in messages
     * transmitted over one-way (e.g., broadcast) data links where retrieval
     * of a resource via a URI is not feasible.
     * Clients intended for use with one-way data links MUST support this
     * element.
     * This element MUST NOT be used unless the sender is certain that all
     * direct clients are capable of processing it.
     * If messages including this element are forwarded onto a two-way
     * network, the forwarder MUST strip the &lt;derefUri&gt; element and SHOULD
     * extract the file contents and provide a &lt;uri&gt; link to a
     * retrievable version of the file.
     * Providers of one-way data links MAY enforce additional restrictions
     * on the use of this element, including message-size limits and
     * restrictions regarding file types.
     * Added in CAP 1.1
     * </pre>
     *
     * <code>optional string deref_uri = 5;</code>
     */
    public com.google.protobuf.ByteString
        getDerefUriBytes() {
      java.lang.Object ref = derefUri_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        derefUri_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The base-64 encoded data content of the resource file.
     * MAY be used either with or instead of the &lt;uri&gt; element in messages
     * transmitted over one-way (e.g., broadcast) data links where retrieval
     * of a resource via a URI is not feasible.
     * Clients intended for use with one-way data links MUST support this
     * element.
     * This element MUST NOT be used unless the sender is certain that all
     * direct clients are capable of processing it.
     * If messages including this element are forwarded onto a two-way
     * network, the forwarder MUST strip the &lt;derefUri&gt; element and SHOULD
     * extract the file contents and provide a &lt;uri&gt; link to a
     * retrievable version of the file.
     * Providers of one-way data links MAY enforce additional restrictions
     * on the use of this element, including message-size limits and
     * restrictions regarding file types.
     * Added in CAP 1.1
     * </pre>
     *
     * <code>optional string deref_uri = 5;</code>
     */
    public Builder setDerefUri(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
      derefUri_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The base-64 encoded data content of the resource file.
     * MAY be used either with or instead of the &lt;uri&gt; element in messages
     * transmitted over one-way (e.g., broadcast) data links where retrieval
     * of a resource via a URI is not feasible.
     * Clients intended for use with one-way data links MUST support this
     * element.
     * This element MUST NOT be used unless the sender is certain that all
     * direct clients are capable of processing it.
     * If messages including this element are forwarded onto a two-way
     * network, the forwarder MUST strip the &lt;derefUri&gt; element and SHOULD
     * extract the file contents and provide a &lt;uri&gt; link to a
     * retrievable version of the file.
     * Providers of one-way data links MAY enforce additional restrictions
     * on the use of this element, including message-size limits and
     * restrictions regarding file types.
     * Added in CAP 1.1
     * </pre>
     *
     * <code>optional string deref_uri = 5;</code>
     */
    public Builder clearDerefUri() {
      bitField0_ = (bitField0_ & ~0x00000010);
      derefUri_ = getDefaultInstance().getDerefUri();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The base-64 encoded data content of the resource file.
     * MAY be used either with or instead of the &lt;uri&gt; element in messages
     * transmitted over one-way (e.g., broadcast) data links where retrieval
     * of a resource via a URI is not feasible.
     * Clients intended for use with one-way data links MUST support this
     * element.
     * This element MUST NOT be used unless the sender is certain that all
     * direct clients are capable of processing it.
     * If messages including this element are forwarded onto a two-way
     * network, the forwarder MUST strip the &lt;derefUri&gt; element and SHOULD
     * extract the file contents and provide a &lt;uri&gt; link to a
     * retrievable version of the file.
     * Providers of one-way data links MAY enforce additional restrictions
     * on the use of this element, including message-size limits and
     * restrictions regarding file types.
     * Added in CAP 1.1
     * </pre>
     *
     * <code>optional string deref_uri = 5;</code>
     */
    public Builder setDerefUriBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
      derefUri_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object digest_ = "";
    /**
     * <pre>
     * The code representing the digital digest (?hash?) computed from the
     * resource from the resource file. Calculated using the Secure Hash
     * Algorithm (SHA-1) per [FIPS 180-2]
     * </pre>
     *
     * <code>optional string digest = 6;</code>
     */
    public boolean hasDigest() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <pre>
     * The code representing the digital digest (?hash?) computed from the
     * resource from the resource file. Calculated using the Secure Hash
     * Algorithm (SHA-1) per [FIPS 180-2]
     * </pre>
     *
     * <code>optional string digest = 6;</code>
     */
    public java.lang.String getDigest() {
      java.lang.Object ref = digest_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          digest_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The code representing the digital digest (?hash?) computed from the
     * resource from the resource file. Calculated using the Secure Hash
     * Algorithm (SHA-1) per [FIPS 180-2]
     * </pre>
     *
     * <code>optional string digest = 6;</code>
     */
    public com.google.protobuf.ByteString
        getDigestBytes() {
      java.lang.Object ref = digest_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        digest_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The code representing the digital digest (?hash?) computed from the
     * resource from the resource file. Calculated using the Secure Hash
     * Algorithm (SHA-1) per [FIPS 180-2]
     * </pre>
     *
     * <code>optional string digest = 6;</code>
     */
    public Builder setDigest(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
      digest_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The code representing the digital digest (?hash?) computed from the
     * resource from the resource file. Calculated using the Secure Hash
     * Algorithm (SHA-1) per [FIPS 180-2]
     * </pre>
     *
     * <code>optional string digest = 6;</code>
     */
    public Builder clearDigest() {
      bitField0_ = (bitField0_ & ~0x00000020);
      digest_ = getDefaultInstance().getDigest();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The code representing the digital digest (?hash?) computed from the
     * resource from the resource file. Calculated using the Secure Hash
     * Algorithm (SHA-1) per [FIPS 180-2]
     * </pre>
     *
     * <code>optional string digest = 6;</code>
     */
    public Builder setDigestBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
      digest_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:publicalerts.cap.Resource)
  }

  // @@protoc_insertion_point(class_scope:publicalerts.cap.Resource)
  private static final com.google.publicalerts.cap.Resource DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.publicalerts.cap.Resource();
  }

  public static com.google.publicalerts.cap.Resource getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<Resource>
      PARSER = new com.google.protobuf.AbstractParser<Resource>() {
    @java.lang.Override
    public Resource parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Resource(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Resource> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Resource> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.publicalerts.cap.Resource getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

