// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cap.proto

package com.google.publicalerts.cap;

public interface ValuePairOrBuilder extends
    // @@protoc_insertion_point(interface_extends:publicalerts.cap.ValuePair)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required string value_name = 1;</code>
   */
  boolean hasValueName();
  /**
   * <code>required string value_name = 1;</code>
   */
  java.lang.String getValueName();
  /**
   * <code>required string value_name = 1;</code>
   */
  com.google.protobuf.ByteString
      getValueNameBytes();

  /**
   * <code>required string value = 2;</code>
   */
  boolean hasValue();
  /**
   * <code>required string value = 2;</code>
   */
  java.lang.String getValue();
  /**
   * <code>required string value = 2;</code>
   */
  com.google.protobuf.ByteString
      getValueBytes();
}
